server:
  port: ${PORT:5000}

base-url: /v1

logging:
  level:
    root: INFO

spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/postgres
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop