version: '3.8'
services:
  app:
    build:
      dockerfile: Dockerfile
    environment:
      - PORT=5000
      - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/postgres
    image: 'tech_app'
    ports:
      - 5000:5000